export interface Service {
  id: string
  num: string
  title: string
  description: string
  image: string
  images?: string[]
  longDescription: string
  detailedContent?: {
    overview: string
    process: string
    quality: string
  }
  features: string[]
  applications: string[]
  benefits: string[]
  specifications?: string[]
  industries?: string[]
  tags: string[]
  category: string
}

export const servicesData: Service[] = [
  {
    id: 'engineering-design-consultation',
    num: '01',
    title: 'Engineering Design & Consultation',
    description: 'Engineering studies, design calculations, project drawings, re-engineering solutions, and metal construction consulting.',
    image: '/service-engineering-design.jpg',
    longDescription: 'Our engineering design and consultation services provide comprehensive solutions for metal construction projects. From initial concept to detailed drawings, our experienced engineers deliver precise calculations, innovative designs, and expert consulting to ensure your project meets all technical and regulatory requirements.',
    features: [
      'Engineering studies and feasibility analysis',
      'Detailed design calculations and structural analysis',
      'Complete project drawings and technical documentation',
      'Re-engineering solutions for existing structures',
      'Metal construction consulting and advisory services',
      'Compliance with international standards',
    ],
    applications: [
      'Industrial facilities and manufacturing plants',
      'Commercial buildings and infrastructure',
      'Renovation and retrofit projects',
      'Custom metal structure design',
    ],
    benefits: [
      'Expert engineering guidance from concept to completion',
      'Optimized designs for cost-effectiveness',
      'Compliance with safety and quality standards',
      'Reduced project risks and delays',
    ],
    tags: ['Engineering Studies', 'Design Calculations', 'Project Drawings', 'Re-engineering Solutions'],
    category: 'Engineering & Design',
  },
  {
    id: 'steel-fabrication',
    num: '02',
    title: 'Steel Fabrication',
    description: 'Mild Steel (MS) Fabrication, Galvanized Steel (GMS), Structural Steel Works, and Custom Steel Fabrication.',
    image: '/service-steel-fabrication.jpg',
    longDescription: 'Our steel fabrication services cover a wide range of materials and applications. We specialize in mild steel, galvanized steel, and structural steel works, providing custom fabrication solutions that meet the highest industry standards. From cutting and forming to welding and assembly, we deliver precision-crafted steel components for any project.',
    features: [
      'Mild Steel (MS) fabrication for general applications',
      'Galvanized Steel (GMS) for corrosion resistance',
      'Structural steel works for buildings and infrastructure',
      'Custom steel fabrication to exact specifications',
      'Advanced welding and joining techniques',
      'Quality inspection and testing',
    ],
    applications: [
      'Building frameworks and structural supports',
      'Industrial equipment and machinery',
      'Storage tanks and containers',
      'Bridges and infrastructure components',
    ],
    benefits: [
      'High strength and durability',
      'Cost-effective material solutions',
      'Versatile fabrication capabilities',
      'Fast turnaround times',
    ],
    tags: ['Mild Steel (MS) Fabrication', 'Galvanized Steel (GMS)', 'Structural Steel Works', 'Custom Steel Fabrication'],
    category: 'Fabrication Services',
  },
  {
    id: 'stainless-steel-fabrication',
    num: '03',
    title: 'Stainless Steel Fabrication',
    description: 'Stainless Steel Structures, custom stainless steel works, and decorative & industrial SS fabrication.',
    image: '/service-stainless-steel.jpg',
    longDescription: 'Stainless steel fabrication services for both decorative and industrial applications. Our expertise includes fabricating stainless steel structures, custom components, and specialized equipment that require superior corrosion resistance, hygiene standards, and aesthetic appeal.',
    features: [
      'Stainless steel structures and frameworks',
      'Custom stainless steel component fabrication',
      'Decorative stainless steel works',
      'Industrial-grade SS fabrication',
      'Polished and brushed finishes',
      'Corrosion-resistant solutions',
    ],
    applications: [
      'Food processing and pharmaceutical facilities',
      'Marine and coastal environments',
      'Architectural and decorative features',
      'Chemical processing equipment',
    ],
    benefits: [
      'Exceptional corrosion resistance',
      'Low maintenance requirements',
      'Hygienic and easy to clean',
      'Long-lasting aesthetic appeal',
    ],
    tags: ['Stainless Steel Structures', 'Custom SS Works', 'Decorative Fabrication', 'Industrial SS'],
    category: 'Fabrication Services',
  },
  {
    id: 'aluminium-fabrication',
    num: '04',
    title: 'Aluminium Fabrication',
    description: 'Aluminium structures, aluminium railings, and comprehensive aluminium fabrication works.',
    image: '/service-aluminium-fabrication.jpg',
    longDescription: 'Specialized aluminium fabrication services offering lightweight yet strong solutions for architectural and industrial applications. Our aluminium works include structures, railings, cladding, and custom components designed for durability and aesthetic excellence.',
    features: [
      'Aluminium structural fabrication',
      'Custom aluminium railings and handrails',
      'Architectural aluminium works',
      'Anodized and powder-coated finishes',
      'Lightweight yet strong solutions',
      'Corrosion-resistant properties',
    ],
    applications: [
      'Commercial building facades',
      'Residential balconies and terraces',
      'Industrial platforms and walkways',
      'Architectural features and decorative elements',
    ],
    benefits: [
      'Lightweight for easy installation',
      'Natural corrosion resistance',
      'Modern aesthetic appeal',
      'Low maintenance and long-lasting',
    ],
    tags: ['Aluminium Structures', 'Aluminium Railings', 'Architectural Works', 'Custom Fabrication'],
    category: 'Fabrication Services',
  },
  {
    id: 'handrails-railing-systems',
    num: '05',
    title: 'Handrails & Railing Systems',
    description: 'Aluminium, Stainless Steel, and Galvanized Steel Handrails, safety railings, and balustrades.',
    image: '/service-handrails-rails.jpg',
    longDescription: 'Comprehensive handrail and railing systems designed for safety, compliance, and aesthetics. We fabricate and install handrails in aluminium, stainless steel, and galvanized steel, suitable for commercial, industrial, and residential applications.',
    features: [
      'Aluminium handrails for modern aesthetics',
      'Stainless steel handrails for premium durability',
      'Galvanized steel handrails for industrial use',
      'Safety railings and barriers',
      'Balustrades for stairs and balconies',
      'Custom designs and finishes',
    ],
    applications: [
      'Staircases and landings',
      'Balconies and terraces',
      'Industrial platforms and walkways',
      'Public buildings and facilities',
    ],
    benefits: [
      'Enhanced safety and fall protection',
      'Compliance with building codes',
      'Durable and weather-resistant',
      'Variety of material and design options',
    ],
    tags: ['Aluminium Handrails', 'Stainless Steel Handrails', 'Safety Railings', 'Balustrades'],
    category: 'Safety Systems',
  },
  {
    id: 'industrial-metal-works',
    num: '06',
    title: 'Industrial Metal Works',
    description: 'Industrial platforms, walkways, staircases, steel gratings, and access platforms.',
    image: '/service-industrial-metal.jpg',
    longDescription: 'Heavy-duty industrial metal works designed for demanding environments. We fabricate and install industrial platforms, walkways, staircases, steel gratings, and access systems that meet stringent safety and load-bearing requirements.',
    features: [
      'Industrial platforms for equipment access',
      'Metal walkways and catwalks',
      'Industrial staircases and ladders',
      'Steel gratings for flooring and drainage',
      'Access platforms for maintenance',
      'Load-rated structures',
    ],
    applications: [
      'Manufacturing plants and factories',
      'Oil and gas facilities',
      'Power generation plants',
      'Warehouses and distribution centers',
    ],
    benefits: [
      'High load-bearing capacity',
      'Safe and efficient access solutions',
      'Durable construction for harsh environments',
      'Compliance with industrial safety standards',
    ],
    tags: ['Industrial Platforms', 'Walkways', 'Steel Gratings', 'Access Platforms'],
    category: 'Industrial Solutions',
  },
  {
    id: 'commercial-residential-staircases',
    num: '07',
    title: 'Commercial & Residential Staircases',
    description: 'Steel staircases, stainless steel staircases, aluminium staircases, and custom stair systems.',
    image: '/service-staircases.jpg',
    longDescription: 'Custom-designed staircases for commercial and residential properties. We create stunning stair systems using steel, stainless steel, and aluminium, combining structural integrity with architectural beauty.',
    features: [
      'Steel staircases for strength and stability',
      'Stainless steel staircases for modern elegance',
      'Aluminium staircases for lightweight solutions',
      'Custom stair designs and configurations',
      'Spiral, straight, and curved staircases',
      'Complete handrail and balustrade integration',
    ],
    applications: [
      'Commercial offices and retail spaces',
      'Residential homes and apartments',
      'Hotels and hospitality venues',
      'Public buildings and institutions',
    ],
    benefits: [
      'Custom designs to match your vision',
      'Durable and safe construction',
      'Variety of material and finish options',
      'Professional installation services',
    ],
    tags: ['Steel Staircases', 'Stainless Steel Stairs', 'Aluminium Stairs', 'Custom Stair Systems'],
    category: 'Architectural Solutions',
  },
  {
    id: 'fencing-systems',
    num: '08',
    title: 'Fencing Systems',
    description: 'Security fencing, mesh fencing, barricade systems, and boundary walls.',
    image: '/service-fencing-systems.jpg',
    longDescription: 'Comprehensive fencing solutions for security, boundary demarcation, and safety. We install various fencing systems including security fencing, mesh fencing, barricades, and boundary walls tailored to your specific requirements.',
    features: [
      'Security fencing for perimeter protection',
      'Mesh fencing for industrial sites',
      'Barricade systems for crowd control',
      'Boundary walls and barriers',
      'Chain link and welded mesh options',
      'Anti-climb and high-security designs',
    ],
    applications: [
      'Industrial facilities and warehouses',
      'Construction sites and temporary barriers',
      'Commercial properties and parking areas',
      'Residential compounds and communities',
    ],
    benefits: [
      'Enhanced security and access control',
      'Durable and weather-resistant',
      'Quick installation and deployment',
      'Cost-effective perimeter solutions',
    ],
    tags: ['Security Fencing', 'Mesh Fencing', 'Barricade Systems', 'Boundary Walls'],
    category: 'Security Solutions',
  },
  {
    id: 'acoustic-barrier-works',
    num: '09',
    title: 'Acoustic Barrier Works',
    description: 'Industrial noise barriers and acoustic wall systems for effective sound control.',
    image: '/service-acoustic-barriers.jpg',
    longDescription: 'Professional acoustic barrier solutions designed to reduce noise pollution in industrial and commercial environments. Our acoustic wall systems effectively control sound transmission while maintaining aesthetic appeal and structural integrity.',
    features: [
      'Industrial noise barriers for factories',
      'Acoustic wall systems for perimeter control',
      'Sound-absorbing panel installation',
      'Custom-designed acoustic solutions',
      'Weather-resistant materials',
      'Compliance with noise regulations',
    ],
    applications: [
      'Manufacturing plants and industrial facilities',
      'Highway and transportation corridors',
      'Power plants and mechanical equipment areas',
      'Commercial properties near residential zones',
    ],
    benefits: [
      'Effective noise reduction',
      'Improved working environment',
      'Regulatory compliance',
      'Enhanced community relations',
    ],
    tags: ['Industrial Noise Barriers', 'Acoustic Wall Systems', 'Sound Control', 'Noise Reduction'],
    category: 'Acoustic Solutions',
  },
  {
    id: 'acoustic-louvers',
    num: '10',
    title: 'Acoustic Louvers',
    description: 'Acoustic louvers, ventilation louvers, and noise control solutions.',
    image: '/service-acoustic-louvers.jpg',
    longDescription: 'Specialized acoustic louvers that combine ventilation requirements with noise control. Our louver systems allow airflow while significantly reducing sound transmission, making them ideal for mechanical equipment enclosures and building ventilation.',
    features: [
      'Acoustic louvers for noise reduction',
      'Ventilation louvers for airflow',
      'Combined acoustic and ventilation solutions',
      'Custom-designed louver systems',
      'Weather-resistant construction',
      'Various blade configurations',
    ],
    applications: [
      'Generator and equipment enclosures',
      'HVAC system openings',
      'Industrial ventilation systems',
      'Building mechanical rooms',
    ],
    benefits: [
      'Effective noise control with ventilation',
      'Reduced equipment noise emissions',
      'Improved air circulation',
      'Durable and low-maintenance',
    ],
    tags: ['Acoustic Louvers', 'Ventilation Louvers', 'Noise Control', 'Equipment Enclosures'],
    category: 'Acoustic Solutions',
  },
  {
    id: 'pipe-anchor-supports',
    num: '11',
    title: 'Pipe Anchor Supports',
    description: 'Pipe support fabrication, anchor support systems, and industrial pipe structures.',
    image: '/service-pipe-anchors.jpg',
    longDescription: 'Precision-engineered pipe anchor supports and support systems for industrial piping infrastructure. Our fabrication services ensure proper pipe alignment, load distribution, and thermal expansion accommodation for reliable piping systems.',
    features: [
      'Custom pipe support fabrication',
      'Anchor support systems for fixed points',
      'Pipe shoe and saddle fabrication',
      'Spring hangers and constant supports',
      'Structural steel pipe racks',
      'Load calculation and design',
    ],
    applications: [
      'Oil and gas facilities',
      'Chemical processing plants',
      'Power generation facilities',
      'Industrial piping systems',
    ],
    benefits: [
      'Proper pipe alignment and support',
      'Accommodation of thermal expansion',
      'Reduced pipe stress and fatigue',
      'Extended piping system life',
    ],
    tags: ['Pipe Support Fabrication', 'Anchor Support Systems', 'Industrial Pipe Structures', 'Pipe Racks'],
    category: 'Industrial Solutions',
  },
  {
    id: 'machine-turning-works',
    num: '12',
    title: 'Machine Turning Works',
    description: 'Precision turning, lathe machine works, and custom machining for high-quality components.',
    image: '/service-machine-turning.jpg',
    longDescription: 'High-precision machine turning services for cylindrical components and custom parts. Our CNC and manual lathe operations deliver tight tolerances and superior surface finishes for critical applications.',
    features: [
      'Precision CNC turning operations',
      'Manual lathe machine works',
      'Custom component machining',
      'Cylindrical part production',
      'Thread cutting and grooving',
      'Tight tolerance capabilities',
    ],
    applications: [
      'Automotive components',
      'Industrial machinery parts',
      'Bearing and shaft components',
      'Custom replacement parts',
    ],
    benefits: [
      'High precision and accuracy',
      'Superior surface finishes',
      'Quick turnaround for custom parts',
      'Quality control and inspection',
    ],
    tags: ['Precision Turning', 'Lathe Machine Works', 'Custom Machining', 'CNC Turning'],
    category: 'Machining Services',
  },
  {
    id: 'metal-bending-works',
    num: '13',
    title: 'Metal Bending Works',
    description: 'Sheet metal bending, custom metal forming, and fabrication bending services.',
    image: '/service-metal-bending.jpg',
    longDescription: 'Professional metal bending services for various materials and applications. Using modern press brakes and forming equipment, we create precise bends and forms in sheet metal and plate materials to your exact specifications.',
    features: [
      'Sheet metal bending and forming',
      'Custom metal forming services',
      'Press brake operations',
      'Angle, channel, and profile bending',
      'Multi-axis bending capabilities',
      'Precision bend angles',
    ],
    applications: [
      'Enclosure and cabinet fabrication',
      'Architectural metal panels',
      'Industrial equipment components',
      'Custom metal brackets and supports',
    ],
    benefits: [
      'Precise and consistent bends',
      'Wide range of material capabilities',
      'Cost-effective forming solutions',
      'Quick turnaround times',
    ],
    tags: ['Sheet Metal Bending', 'Custom Metal Forming', 'Press Brake Services', 'Fabrication Bending'],
    category: 'Fabrication Services',
  },
]
